export const itemData = [
    {
        id: "0001",
        category: "earrings",
        article: "Classic Gold Studs",
        price: 120.00,
        date: "2025-12-15",
        rating: 90,
        src: "./images/shop/earings/gold.webp",
        description: "Clean and timeless, these gold studs are designed for everyday wear. Lightweight and versatile, they add a subtle touch of elegance to any outfit.",
    },
    {
        id: "0002",
        category: "earrings",
        article: "Gold Studs",
        price: 125.00,
        date: "2026-01-01",
        rating: 86,
        src: "./images/shop/earings/gold2.webp",
        description: "Clean and timeless, these gold studs are designed for everyday wear. Lightweight and versatile, they add a subtle touch of elegance to any outfit.",
    },
    {
        id: "0003",
        category: "earrings",
        article: "Pearl Drop",
        price: 39.99,
        date: "2026-02-25",
        rating: 84,
        src: "./images/shop/earings/pearldrop.webp",
        description: "Delicate pearls suspended on a fine setting create a soft, refined look. Ideal for adding a hint of sophistication without being overwhelming.",
    },
    {
        id: "0004",
        category: "earrings",
        article: "Ear Spike",
        price: 49.99,
        date: "2026-02-15",
        rating: 83,
        src: "./images/shop/earings/spike.webp",
        description: "A simple design that speaks through clean lines. These earrings are perfect for those who appreciate understated beauty.",
    },
    {
        id: "0005",
        category: "earrings",
        article: "Dangle",
        price: 69.99,
        date: "2026-02-16",
        rating: 83,
        src: "./images/shop/earings/dangle.webp",
        description: "Lightweight and elegant, these dangle earrings are designed to move with you. Their clean, minimal silhouette adds a soft statement to any look—perfect for both everyday wear and special occasions.",
    },
    {
        id: "0006",
        category: "earrings",
        article: "Hoop",
        price: 79.99,
        date: "2026-03-2",
        rating: 92,
        src: "./images/shop/earings/hoop.webp",
        description: "Clean and timeless, these hoop earrings offer a refined, minimalist look. Lightweight and easy to wear, they bring effortless balance to both everyday and elevated styles.",
    },
    {
        id: "1001",
        category: "necklace",
        article: "Plastron",
        price: 100.00,
        date: "2025-12-15",
        rating: 90,
        src: "./images/shop/necklace/necklace1.webp",
        description: "A bold yet clean statement, this plastron necklace features a structured silhouette that rests gracefully along the neckline. Its minimalist design brings modern elegance while maintaining a refined, understated look.",
    },
    {
        id: "1002",
        category: "necklace",
        article: "Chain",
        price: 29.99,
        date: "2026-01-01",
        rating: 80,
        src: "./images/shop/necklace/chain.webp",
        description: "A modern blend of structure and simplicity, this hoop chain necklace features clean links and a refined silhouette. Lightweight and versatile, it adds a subtle edge to both everyday and elevated looks.",
    },
    {
        id: "1003",
        category: "necklace",
        article: "Pearl",
        price: 59.99,
        date: "2026-04-25",
        rating: 80,
        src: "./images/shop/necklace/pearl.webp",
        description: "Timeless and understated, this pearl necklace brings a soft, refined elegance to any look. Designed with a clean silhouette, it’s perfect for everyday wear or subtle occasions.",
    },
    {
        id: "1004",
        category: "necklace",
        article: "Birthstone",
        price: 89.99,
        date: "2026-04-15",
        rating: 87,
        src: "./images/shop/necklace/birthstone.webp",
        description: "Personal and refined, this birthstone necklace features a delicate setting with a touch of color. Designed to be meaningful yet minimal, it adds a subtle, elegant accent to everyday wear.",
    },
    {
        id: "2001",
        category: "bracelet",
        article: "Beaded",
        price: 125.00,
        date: "2025-12-15",
        rating: 87,
        src: "./images/shop/bracelet/beaded.webp",
        description: "Simple and refined, this beaded bracelet features a clean arrangement of delicate beads for a balanced, minimalist look. Lightweight and versatile, it’s perfect for everyday wear or subtle layering.",
    },
    {
        id: "2002",
        category: "bracelet",
        article: "Braided",
        price: 49.99,
        date: "2026-1-5",
        rating: 85,
        src: "./images/shop/bracelet/braided.webp",
        description: "Clean and understated, this braided bracelet features a simple woven design that adds subtle texture. Lightweight and easy to wear, it offers a relaxed, minimalist touch to any look.",
    },
    {
        id: "2003",
        category: "bracelet",
        article: "Charm",
        price: 100.00,
        date: "2026-2-15",
        rating: 88,
        src: "./images/shop/bracelet/charm.webp",
        description: "Delicate and personal, this charm bracelet features a clean chain with subtle accents. Designed for everyday wear, it adds a quiet touch of character while keeping a refined, minimalist look.",
    },
    {
        id: "2004",
        category: "bracelet",
        article: "Chain",
        price: 39.99,
        date: "2026-3-08",
        rating: 80,
        src: "./images/shop/bracelet/chain.webp",
        description: "Clean and versatile, this chain bracelet features a refined link design with a smooth, minimalist finish. Lightweight and easy to style, it adds a subtle touch of polish to any look.",
    },
    {
        id: "3001",
        category: "ring",
        article: "Three Stone",
        price: 75.00,
        date: "2025-12-15",
        rating: 90,
        src: "./images/shop/rings/threeStone.webp",
        description: "Balanced and refined, this three stone ring features a clean, symmetrical design with subtle brilliance. Understated yet meaningful, it adds a quiet elegance to both everyday wear and special moments.",
    },
    {
        id: "3002",
        category: "ring",
        article: "Solitaire",
        price: 129.99,
        date: "2025-2-15",
        rating: 85,
        src: "./images/shop/rings/solitaire.webp",
        description: "Simple and timeless, this solitaire ring features a single stone set in a clean, refined design. Elegant and understated, it offers a subtle brilliance perfect for everyday wear or special moments.",
    },
    {
        id: "3003",
        category: "ring",
        article: "Diamon Band",
        price: 250.00,
        date: "2025-3-15",
        rating: 88,
        src: "./images/shop/rings/diamondBand.webp",
        description: "Sleek and refined, this diamond band ring features a continuous line of subtle sparkle. Designed with a clean, minimalist profile, it adds effortless elegance to everyday wear or layering.",
    },
    {
        id: "3004",
        category: "ring",
        article: "Mood",
        price: 89.99,
        date: "2026-4-15",
        rating: 82,
        src: "./images/shop/rings/mood.webp",
        description: "Playful yet refined, this mood ring features a clean design with a subtle color-changing center. Minimal in form, it adds a quiet touch of personality to your everyday look.",
    },
    {
        id: "4001",
        category: "bangle",
        article: "Solid Metal",
        price: 69.99,
        date: "2025-12-03",
        rating: 90,
        src: "./images/shop/bangles/solidMetal.webp",
        description: "Clean and timeless, these solid metal bangles feature a smooth, structured design with a minimalist finish. Durable and versatile, they add a refined touch whether worn alone or stacked.",
    },
    {
        id: "4002",
        category: "bangle",
        article: "Cuff",
        price: 99.99,
        date: "2026-1-10",
        rating: 85,
        src: "./images/shop/bangles/cuff.webp",
        description: "Sleek and open-ended, these cuff bangles feature a clean, structured design for effortless wear. Minimal yet bold, they add a refined statement to both everyday and elevated looks.",
    },
    {
        id: "4003",
        category: "bangle",
        article: "Lacquer",
        price: 39.99,
        date: "2026-2-15",
        rating: 88,
        src: "./images/shop/bangles/lacquer.webp",
        description: "Smooth and refined, these lacquer bangles feature a clean, glossy finish with a minimalist silhouette. Lightweight and versatile, they add a subtle touch of color and polish to any look.",
    },
    {
        id: "4004",
        category: "bangle",
        article: "Hinged",
        price: 59.99,
        date: "2026-4-01",
        rating: 80,
        src: "./images/shop/bangles/hinged.webp",
        description: "Clean and structured, these hinged bangles feature a smooth silhouette with an easy open-and-close design. Minimal yet refined, they offer a polished touch for both everyday wear and elevated looks.",
    },
    {
        id: "5001",
        category: "tiara",
        article: "Fringe",
        price: 119.99,
        date: "2025-11-15",
        rating: 92,
        src: "./images/shop/tiara/fringe.webp",
        description: "Delicate yet striking, this fringed tiara features fine, cascading elements in a clean, structured design. Light-catching and refined, it adds a subtle statement with a minimalist elegance.",
    },
    {
        id: "5002",
        category: "tiara",
        article: "Meander",
        price: 149.99,
        date: "2025-12-01",
        rating: 88,
        src: "./images/shop/tiara/meander.webp",
        description: "Structured and timeless, this meander tiara features a clean Greek key pattern with a refined, geometric flow. Minimal yet distinctive, it brings a subtle sense of symmetry and elegance to any look.",
    },
    {
        id: "5003",
        category: "tiara",
        article: "Aigrette",
        price: 175.00,
        date: "2026-1-15",
        rating: 87,
        src: "./images/shop/tiara/aigrette.webp",
        description: "Graceful and refined, this aigrette tiara features a feather-like silhouette with delicate, flowing lines. Light-catching and elegant, it adds a subtle statement while maintaining a minimalist feel.",
    },
    {
        id: "5004",
        category: "tiara",
        article: "Bandeau",
        price: 160.00,
        date: "2026-2-15",
        rating: 85,
        src: "./images/shop/tiara/bandeau.webp",
        description: "Sleek and structured, this bandeau tiara features a clean, low-profile design that sits gracefully along the head. Minimal yet refined, it offers a modern take on classic elegance.",
    },
    {
        id: "6001",
        category: "anklet",
        article: "String",
        price: 29.99,
        date: "2025-12-05",
        rating: 89,
        src: "./images/shop/anklet/stringAnklet.webp",
        description: "Light and effortless, this string anklet features a fine cord design with a clean, minimalist finish. Subtle and versatile, it adds a relaxed touch of elegance to everyday wear.",
    },
    {
        id: "6002",
        category: "anklet",
        article: "Beaded",
        price: 39.99,
        date: "2025-12-20",
        rating: 85,
        src: "./images/shop/anklet/beadedAnklet.webp",
        description: "Delicate and refined, this beaded anklet features a simple arrangement of fine beads for a clean, balanced look. Minimal yet expressive, it adds a subtle touch of texture to everyday wear.",
    },
    {
        id: "6003",
        category: "anklet",
        article: "Braided",
        price: 49.99,
        date: "2026-2-15",
        rating: 88,
        src: "./images/shop/anklet/beadedAnklet.webp",
        description: "Simple and textured, this braided anklet features a clean woven design with a soft, minimalist finish. Lightweight and easy to wear, it adds a relaxed, understated touch to any look.",
    },
    {
        id: "6004",
        category: "anklet",
        article: "Demi-fine",
        price: 59.99,
        date: "2026-2-15",
        rating: 82,
        src: "./images/shop/anklet/demiFineAnklet.webp",
        description: "Refined and delicate, this demi-fine anklet features a slim chain with subtle detailing in a clean, minimalist design. Light-catching yet understated, it adds a polished touch to everyday wear.",
    },
    {
        id: "7001",
        category: "other",
        article: "Gold Plated Wrist Watch",
        price: 129.99,
        date: "2025-12-20",
        rating: 90,
        src: "./images/shop/others/watch.webp",
        description: "Sleek and refined, this gold-plated wrist watch features a clean dial and a polished finish. Minimal in design, it offers a timeless look that transitions effortlessly from everyday wear to formal occasions.",
    },
    {
        id: "7002",
        category: "other",
        article: "Gold Plated Pocket Watch",
        price: 299.99,
        date: "2026-1-15",
        rating: 89,
        src: "./images/shop/others/pocket.webp",
        description: "Classic and refined, this gold-plated pocket watch features a clean dial and a polished finish. Minimal yet timeless, it offers a subtle vintage touch with effortless elegance.",
    },
    {
        id: "7003",
        category: "other",
        article: "Gold Plated Belt",
        price: 39.99,
        date: "2026-2-15",
        rating: 84,
        src: "./images/shop/others/belt.webp",
        description: "Clean and understated, this gold belt features a sleek finish with a refined buckle detail. Minimal in design, it adds a subtle touch of polish to both everyday and elevated looks.",
    },
    {
        id: "7004",
        category: "other",
        article: "Gold Plated Lighter",
        price: 29.99,
        date: "2026-3-15",
        rating: 87,
        src: "./images/shop/others/lighter.webp",
        description: "Sleek and refined, this gold-plated lighter features a clean, polished finish in a minimalist design. Compact and elegant, it adds a subtle touch of sophistication to everyday essentials.",
    },
];

